security:
    encoders:
        App\Entity\Main\User:
            algorithm: bcrypt

    providers:
        rdig_db_provider:
            entity:
                class: App\Entity\Main\User
                property: username

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout:
                target: /logoutSuccess
            guard:
                authenticators:
                    - app.simple_authenticator
            #json_login:
                #check_path: /login
            #pattern:    ^/
            # http_basic: ~
            provider: rdig_db_provider

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_decision_manager:
            strategy: unanimous
            allow_if_all_abstain: false