#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin__user__create:
    path:       /admin/{entityName}
    controller: App\Controller\UserCrudController::create
    methods:    [POST]
    requirements:
            entityName: 'user'

admin__user__list:
    path:       /admin/{entityName}
    controller: App\Controller\UserCrudController::list
    methods:    [GET]
    requirements:
            entityName: 'user'

admin__user__read:
    path:       /admin/{entityName}/{id}
    controller: App\Controller\UserCrudController::read
    methods:    [GET]
    requirements:
            entityName: 'user'
            id: '\d+'

admin__user__change-password:
    path:       /admin/{entityName}/{id}/change-password
    controller: App\Controller\UserCrudController::changePassword
    methods:    [POST]
    requirements:
            entityName: 'user'
            id: '\d+'

admin__user__delete:
    path:       /admin/{entityName}/{id}
    controller: App\Controller\UserCrudController::delete
    methods:    [DELETE]
    requirements:
            entityName: 'user'

data__crud__create:
    path:       /data/{entityName}
    controller: App\Controller\DataCrudController::create
    methods:    [POST]
    requirements:
            entityName: '[\w\-?]+'

data__crud__list:
    path:       /data/{entityName}
    controller: App\Controller\DataCrudController::list
    methods:    [GET]
    requirements:
            entityName: '[\w\-?]+'

data__crud__read:
    path:       /data/{entityName}/{id}
    controller: App\Controller\DataCrudController::read
    methods:    [GET]
    requirements:
            entityName: '[\w\-?]+'
            id: '\d+'

data__crud__put:
    path:       /data/{entityName}/{id}
    controller: App\Controller\DataCrudController::update
    methods:    [PUT]
    requirements:
            entityName: '[\w\-?]+'
            id: '\d+'

data__crud__delete:
    path:       /data/{entityName}/{id}
    controller: App\Controller\DataCrudController::delete
    methods:    [DELETE]
    requirements:
            entityName: '[\w\-?]+'
            id: '\d+'
